channels:
- conda-forge
dependencies:
- python=3.14.4
- pip<=26.0.1
- pip:
  - mlflow==3.16.0
  - dill==0.4.1
  - numpy==2.4.4
  - pandas==3.0.2
  - psutil==7.0.0
  - pyarrow==24.0.0
  - scikit-learn==1.8.0
  - scipy==1.17.1
  - skops==0.14.0
  - torch==2.11.0
  - tqdm==4.67.3
name: mlflow-env
